apiVersion: v1
kind: Service
metadata:
  name: {{ include "national-portal-fe.fullname" . }}
  labels:
    {{- include "national-portal-fe.labels" . | nindent 4 }}
    prometheus.io/monitor: nginx-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9113
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "national-portal-fe.selectorLabels" . | nindent 4 }}
