{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "national-portal-fe.serviceAccountName" . }}
  labels:
{{ include "national-portal-fe.labels" . | nindent 4 }}
{{- end -}}
