# - op: replace
#   path: /spec/rules/0/http/paths/0/path
#   value:
#     path: /app

# - op: add
#   path: /spec/rules/-
#   value:
#     host: <CHARTNAME>.ads1.itpartner.no
#     http:
#       paths:
#        - path: /
#          pathType: Prefix
#          backend:
#            service:
#              name: <deploy_name>
#              port:
#                number: 80
# - op: add
#   path: /spec/tls/0/hosts/-
#   value: <CHARTNAME>.ads1.itpartner.no
